Models/Enroll.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace KOI_System.Models
{
    public class Enroll
    {
        [Display(Name = "ID")]
        public int ID { get; set; }

        [Required(ErrorMessage = "Please enter FirstName")]
        [Display(Name = "FirstName")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Please enter LastName")]
        [Display(Name = "LastName")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Please enter password")]
        [DataType(DataType.Password)]
        [StringLength(100, ErrorMessage = "Password \"{0}\" must have {2} character", MinimumLength = 8)]
        [RegularExpression(@"^([a-zA-Z0-9@*#]{8,15})$", ErrorMessage = "Password must contain: Minimum 8 characters atleast 1 UpperCase Alphabet, 1 LowerCase      Alphabet, 1 Number and 1 Special Character")]
        public string Password { get; set; }

        [Display(Name = "Confirm password")]
        [Required(ErrorMessage = "Please enter confirm password")]
        [Compare("Password", ErrorMessage = "Confirm password doesn't match, Type again !")]
        [DataType(DataType.Password)]
        public string Confirmpwd { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }

        [Display(Name = "Gender")]
        [Required(ErrorMessage = "Please Select the gender")]
        public string Gender { get; set; }

        [Required]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "E-mail id is not valid")]
        public string Email { get; set; }

        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Phone Number")]
        [Required(ErrorMessage = "Phone Number Required!")]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Entered phone format is not valid.")]
        public string PhoneNumber { get; set; }

        [Required(ErrorMessage = "Please enter Security Answer")]
        [Display(Name = "Security Answer")]
        public string SecurityAnwser { get; set; }

        public List<Enroll> Enrollsinfo { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace KOI_System.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Event.cs
using System.ComponentModel.DataAnnotations;
using KOI_System.Models;
using System;
using System.Collections.Generic;
using System.Text;

namespace KOI_System.Models
{
    public class Event
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Image { get; set; }
        public string Details { get; set; }
        public string Venue { get; set; }
        public string Date { get; set; }
    }
}

Models/Events.cs
using System.ComponentModel.DataAnnotations;
using KOI_System.Models;
using System;
using System.Collections.Generic;
using System.Text;

namespace KOI_System.Models
{
    public class Events
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Image { get; set; }
        public string Details { get; set; }
        public string Venue { get; set; }
        public string Date { get; set; }
        public List<Organizer> EventOrganizer { get; set; }
    }
}

Models/Organizer.cs
using KOI_System.Models;
using System;
using System.Collections.Generic;
using System.Text;

namespace KOI_System.Models
{
    public class Organizer
    {
        public int Id { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }

        public ICollection<seminars> Seminars { get; set;  }

        public ICollection<Events> Events { get; set; }
    }
}

Models/Seminar.cs
using System.ComponentModel.DataAnnotations;

namespace KOI_System.Models
{
    public class seminars
    {
        [Key]
        public int Id { get; set; }
        public string Title { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
        public string Venue { get; set; }
        public string Date { get; set; }
    }
}

Models/User.cs
using KOI_System.Models;
using System;
using System.Collections.Generic;
using System.Text;

namespace KOI_System.Models
{
    public class User
    {
        public int Id { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }

        public ICollection<seminars> Seminars { get; set; }

    }
}

Controllers/HomeController.cs
using KOI_System.Context;
using KOI_System.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace KOI_System.Controllers
{
    public class HomeController : Controller
    {
       
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Default()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        public IActionResult Event()
        {
            return View();
        }

        public IActionResult Location()
        {
            return View();
        }

        public IActionResult Record()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/SeminarController.cs
using KOI_System.Context;
using KOI_System.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
namespace KOI_System.Controllers
{
    public class SeminarController : Controller
    {
        MVCContext db;
        public SeminarController(MVCContext _db)
        {
            db = _db;
        }
        public IActionResult Record()
        {
            IEnumerable<seminars> Seminars = db.Seminars.Select(s => s).ToList();

            return View(Seminars);
        }

        public IActionResult Delete(int id)
        {
            seminars Seminar = db.Seminars.FirstOrDefault(s => s.Id == id);
            if(Seminar != null)
            {
                db.Remove(Seminar);
                db.SaveChanges();
                return RedirectToAction("Record");
            }

            return View();
        }
    }
}

Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact Us";
}
<h1>@ViewData["Title"]</h1>

   <div class = "content"><!--body content holder-->
            <div class = "container">
                <div class = "col-md-12"><!--body content title holder with 12 grid columns-->
                   
                </div>
            </div>
			
            <div class="container">
            <div class="col-md-12">
            <hr>
            </div>
            </div>
            
            <div class="container">
                <div class="col-md-6 contacts">
                    <h1><span class="glyphicon glyphicon-user"></span> Erick Omundi</h1>
                    <p>
                        <span class="glyphicon glyphicon-envelope"></span> Email: protech@yahoo.ie<br>
                        <span class="glyphicon glyphicon-link"></span> Facebook: www.facebook.com/protech<br>
                        <span class="glyphicon glyphicon-phone"></span> Mobile: 0123456789
                    </p>
                </div>
                <div class="col-md-6">
                    <form>
                        <div class="form-group">
                            <label for="Title">Title:</label>
                            <input type="text" name="title" id="Title" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="Comment">Message:</label>
                            <textarea id="Comment" rows="10" class="form-control"></textarea>
                        </div>
                        <button type="submit" class="btn btn-default pull-right">Send <span class="glyphicon glyphicon-send"></span></button>
                    </form>
                </div>
            </div>
			
            
        </div><!--body content div-->

Views/Home/Default.cshtml
@{
    ViewData["Title"] = "Home Page";
}
  <div class = "content"><!--body content holder-->
            <div class = "container">
                <div class = "col-md-12"><!--body content title holder with 12 grid columns-->
                    <h1>What we organize</h1><!--body content title-->
                </div>
            </div>
			
            <div class="container">
            <div class="col-md-12">
            <hr>
            </div>
            </div>
			
            <div class="row"><!--wedding content-->
                <section>
                    <div class="container">
                        <div class="col-md-6"><!--image holder with 6 grid columns-->
                            <img src="~/images/wedding2.jpg" class="img-responsive">
                        </div>
                        <div class="subcontent col-md-6"><!--Text holder with 6 column grid-->
                            <h1>Students Seminars</h1><!--title-->
                            <p><!--content-->
                            The most important day in a couple's life.
                            Guaranteeing personalized solutions and flawless execution, our venues provide the perfect
                            location for your special day.
                            </p>
                            <hr class="customline"><!--css modified horizontal line-->
                            <button type="button" class="btn btn-default btn-lg"><!--view event button (no function implemented)-->
                            View Events  <span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span><!--arrow right glyphicon-->
                            </button>
                        </div><!--subcontent div-->
                    </div><!--container div-->
                </section>
            </div><!--row div-->
			
            <div class="container">
            <div class="col-md-12">
            <hr>
            </div>
            </div>

            <div class="row">
                <section>
                    <div class="container">
                        <div class="col-md-6"><!--image holder with 6 grid columns-->
                            <img src="~/images/birthday2.jpg" class="img-responsive">
                        </div>
                        <div class="subcontent col-md-6"><!--Text holder with 6 column grid-->
                            <h1>Faculty Seminars</h1><!--title-->
                            <p><!--content-->
                            Whether an all-day or the ultimate extravaganza that
                            lasts well into the wee hours, our Urban Events team is here to make sure all your birthday
                            party wishes come true so you can kick back, drink up and enjoy your special day!
                            </p>
                            <hr class="customline"><!--css modified horizontal line-->
                            <button type="button" class="btn btn-default btn-lg"><!--view event button (no function implemented)-->
                            View Events  <span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span><!--arrow right glyphicon-->
                            </button>
                        </div><!--subcontent div-->
                    </div><!--container div-->
                </section>
            </div><!--row div-->
			
            <div class="container">
            <div class="col-md-12">
            <hr>
            </div>
            </div>

            <div class="row">
                <section>
                    <div class="container">
                        <div class="col-md-6"><!--image holder with 6 grid columns-->
                            <img src="~/images/fashion2.jpg" class="img-responsive">
                        </div>
                        <div class="subcontent col-md-6"><!--Text holder with 6 column grid-->
                            <h1>Instructors Seminars</h1><!--title-->
                            <p><!--content-->
                            Fast becoming to go-to location for fashion events, PR gatherings and product launches, 
                            The Urban Purveyor Group venues provide you with choice and quality in premium locations 
                            for all your event needs.
                            </p>
                            <hr class="customline"><!--css modified horizontal line-->
                            <button type="button" class="btn btn-default btn-lg"><!--view event button (no function implemented)-->
                            View Events  <span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span><!--arrow right glyphicon-->
                            </button> 
                        </div><!--subcontent div-->
                    </div><!--container div-->
                </section>
            </div><!--row div-->
			
            <div class="container">
            <div class="col-md-12">
                <hr>
            </div>
            </div>

            <div class="row">
                <section>
                    <div class="container">
                        <div class="col-md-6"><!--image holder with 6 grid columns-->
                            <img src="~/images/meeting2.jpg" class="img-responsive">
                        </div>
                        <div class="subcontent col-md-6"><!--Text holder with 6 column grid-->
                            <h1>Employees Seminars</h1><!--title-->
                            <p><!--content-->
                            From formal, to not-so-formal, our flexible event
                            spaces can cater to your every need for meetings and conferences large or small, and our
                            dedicated event team can assist with all aspects of your event planning.
                            </p>
                            <hr class="customline"><!--css modified horizontal line-->
                            <button type="button" class="btn btn-default btn-lg"><!--view event button (no function implemented)-->
                            View Events  <span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span><!--arrow right glyphicon--> 
                            </button> 
                        </div><!--subcontent div-->
                    </div><!--container div-->
                </section>
            </div><!--row div-->
        </div><!--body content div-->

Views/Home/Index.cshtml
@{
    Layout = "_Layouts";
}

<center>
    <table class="content-table">
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Student ID</th>
     
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>1</td>
      <td>Sameer Khanal</td>
      <td>12001043</td>
     
    </tr>
    <tr class="active-row">
      <td>2</td>
      <td>James Pariyar</td>
      <td>12001256</td>
      
    </tr>
  
  </tbody>
</table>
To Access various Seminers & Events  portal <br />
    <a  asp-area="" asp-controller="Home" asp-action="Default" >Click Here</a> 
</center><

Views/Seminar/Record.cshtml
@model IEnumerable<KOI_System.Models.seminars>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Image)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Venue)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Image)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Venue)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - King's Own Institute</title>

    <link rel = "stylesheet" type = "text/css" href = "~/css/bootstrap-theme.css" />
    <link rel = "stylesheet" type = "text/css" href = "~/css/bootstrap-theme.css.map">
    <link rel = "stylesheet" type = "text/css" href = "~/css/bootstrap.css">
    <link rel = "stylesheet" type = "text/css" href = "~/css/bootstrap.css.map">
    <link rel = "stylesheet" type = "text/css" href = "~/css/style.css">

    <link rel = "stylesheet" type = "text/css" href = "~/css/style.css">
      <link rel = "stylesheet" type = "text/css" href = "~/css/style.css">
        <link rel = "stylesheet" type = "text/css" href = "~/css/style.css">
    
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'><!--css links. file found in utils folder-->
        
    <script src="~/js/jquery-1.12.1.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/js.js"></script>

</head>
<body>
   


         <header class="bgImage">
    <nav class="navbar">
        <div class="container">
            <div class="navbar-header"><!--website name/title-->
                <a href = "index.php" class = "navbar-brand">
                    King's Own Institute
                </a>             </div>
            <ul class="nav navbar-nav navbar-right"><!--navigation-->


                   
                <li>
                    <a  asp-area="" asp-controller="Home" asp-action="Default" >Home</a>
                </li>
                <li>
                    <a  asp-area="" asp-controller="Home" asp-action="Event" >Events</a>
                </li>
                <li>
                    <a  asp-area="" asp-controller="Home" asp-action="Location" >Locations</a>
                </li>
                <li>
                    <a  asp-area="" asp-controller="Home" asp-action="Contact" >Contact Us</a>
                </li>
                    <li>
                    <a  asp-area="" asp-controller="Seminar" asp-action="Record" >Add Seminar</a>
                </li>

                <button type = "button" class = "btn btn-default navbar-btn" data-toggle = "modal" data-target = "#loginnn">Info <Span class="glyphicon glyphicon-log-in"></span></button>    
                    
                <div class="modal fade" id="login" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"><!--modal for login-->
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header"><!--modal header-->
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                <h4 class="modal-title" id="myModalLabel">Login</h4><!--modal title-->
                            </div>
                            <div class="row">
                                <div class="modal-body"><!--modal content-->
                                    <div class ="col-md-6 col-md-offset-3">
                                        <form action="login.php" method="POST">
                                            <div class = "form-group"><!--username-->
                                                <label for="username">Username:</label>
                                                <input type="text"
                                                       name="username"
                                                       class="form-control"
                                                       value=""
                                                       />
                                                <span class="error"><!--error message on failed input-->
                                                                                                    </span>
                                            </div>
                                            <div class="form-group"><!--password-->
                                                <label for="password">Password:</label>
                                                <input type="password"
                                                       name="password"
                                                       class="form-control"
                                                       value=""
                                                       />
                                                <span class="error"><!--error message on failed input-->
                                                                                                    </span>
                                            </div>
                                            <button type="submit" class = "btn btn-default loginbtn">Login</button><!--login button-->
                                            <a class="btn btn-default navbar-btn rgsterbtn" href = "register_form.php">Register</a><!--register button-->
                                        </form>
                                    </div>
                                </div><!--modal body div-->
                            </div><!--row div-->
                            <div class="modal-footer"><!--modal footer-->
                            <button type="button" class="btn btn-default closebtn" data-dismiss="modal">Close</button><p><!--close button-->
                            </div><!--modal footer div-->
                        </div><!--modal content div-->
                    </div><!--modal dialog div-->
                </div><!--modal div-->
            </ul>
        </div><!--container div-->
    </nav>
    <div class = "col-md-12">
        <div class = "container">
            <div class = "jumbotron"><!--jumbotron-->
                <h1>KOI Seminars Management System </h1><!--jumbotron heading-->
                <p><!--jumbotron content-->
                Whether you're looking to book a cocktail party, post-work gathering, celebratory function, conference, business
                meeting, wedding or private dining event, our dedicated Urban Events team can create a package that will meet
                your every need.
                </p>
                <p id="dateAndTime"></p>
            </div>
        </div>
    </div>
</header><!--header content. file found in utils folder-->


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

       <hr class = "footerline"><!--css modified horizontal line-->
<footer>
    <div class = "container">
        <div class = "row">
            <section>
                <div class = "footerContent col-md-4"><!--left content-->
                    <p class = "footerContent1">
                        <strong>K</strong><span class = "small footerSubtext">ing's</span>
                        <strong>O</strong><span class = "small footerSubtext">wn</span>
                        <strong>I</strong><span class = "small footerSubtext">nstitute</span>
                       
                    </p>

                    <p class = "footerSubtext2">
                        Kill Avenue, Dun Laoghaire, Co. Dublin
                        &copy; 2022.
                    </p>
                </div>
            </section>
            <section>
                <div class = "footcontent col-md-4"><!--middle content-->
                    DL824 Multimedia Design/Web Engineering<br>
                    Creative Computing 2021-2022.<br>
                    Julz Engracio, N00145647
                </div>
            </section>
            <section>
                <div class = "footcontent col-md-4"><!--right content-->
                    Follow Us:<br>
                        <img src = "~/images/facebook.png">
                        <img src = "~/images/twitter.png">
                        <img src = "~/images/googleplus.png">
                        <img src = "~/images/youtube.png">
                </div>
            </section>
        </div>
    </div>
</footer><!--footer content. file found in utils folder-->
   
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layouts.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - King's Own Institute</title>

    <link rel = "stylesheet" type = "text/css" href = "~/css/sty.css">

	<link href="https://fonts.googleapis.com/css?family=Dancing+Script|Indie+Flower|Montserrat|Quicksand&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

 
</body>
</html>